import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor

def clean_text(text):
    # First, handle special characters
    replacements = {
        "–": "-",  # En dash to hyphen
        "—": "-",  # Em dash to hyphen
        "’": "'",  # Right single quote to straight quote
        "‘": "'",  # Left single quote to straight quote
        "“": '"',  # Left double quote to straight quote
        "”": '"',  # Right double quote to straight quote
        "*": "",  # Remove residual Markdown stars
    }
    for unicode_char, ascii_char in replacements.items():
        text = text.replace(unicode_char, ascii_char)
    
    # Then, handle bullet points and formatting
    text = text.replace(". ", "- ")  # Standardize bullet points
    text = text.replace("•", "-")    # Convert bullet points to hyphens
    text = text.replace("◦", "-")    # Convert sub-bullets to hyphens
    
    # Convert hyphens to colons for better readability
    text = text.replace(" - ", ": ")
    text = text.replace(" -", ": ")
    
    # Clean up any double spaces
    text = " ".join(text.split())
    
    return text.encode("ascii", "ignore").decode("ascii")

def wrap_text(c, text, x, y, max_width, font_name, font_size, line_spacing=12):
    c.setFont(font_name, font_size)
    words = text.split()
    lines = []
    current_line = []
    current_width = 0

    for word in words:
        word_width = c.stringWidth(word + " ", font_name, font_size)
        if current_width + word_width <= max_width:
            current_line.append(word)
            current_width += word_width
        else:
            lines.append(" ".join(current_line))
            current_line = [word]
            current_width = word_width
    if current_line:
        lines.append(" ".join(current_line))

    for line in lines:
        c.drawString(x, y, line)
        y -= line_spacing
    return y

def generate_pdf(roadmap, job_fit_analysis, smart_gap_analysis, effective_role):
    from io import BytesIO
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Enhanced margins and spacing
    left_margin = 1 * inch
    right_margin = 1 * inch
    top_margin = 1 * inch
    bottom_margin = 0.75 * inch
    content_width = width - left_margin - right_margin

    # Enhanced color scheme
    primary_color = HexColor("#4a69bd")    # Main blue
    accent_color = HexColor("#60a5fa")     # Light blue
    text_color = HexColor("#2d2d44")       # Dark gray
    phase_color = HexColor("#1a1a2e")      # Dark blue for phases

    def draw_header():
        # Draw logo with enhanced positioning
        try:
            logo_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "SkillWise.png"))
            logo_width = 1.5 * inch
            logo_height = 0.5 * inch
            logo_x = left_margin
            logo_y = height - 0.7 * inch
            c.drawImage(logo_path, logo_x, logo_y, width=logo_width, height=logo_height, preserveAspectRatio=True)
        except Exception as e:
            print(f"[PDF] Could not load logo at {logo_path}: {e}")
            try:
                c.drawImage("SkillWise.png", logo_x, logo_y, width=logo_width, height=logo_height, preserveAspectRatio=True)
            except Exception as e2:
                print(f"[PDF] Fallback SkillWise.png also failed: {e2}")
            pass
        # Enhanced title styling
        c.setFont("Helvetica-Bold", 24)
        c.setFillColor(primary_color)
        title_x = left_margin + 1.5 * inch + 0.4 * inch
        title_y = height - 0.6 * inch
        c.drawString(title_x, title_y, "SkillWise Learning Roadmap")
        # Decorative line with gradient
        c.setStrokeColor(accent_color)
        c.setLineWidth(2)
        c.line(left_margin, height - 0.8 * inch, width - right_margin, height - 0.8 * inch)

    def draw_footer(page_num):
        # Enhanced footer design
        c.setFont("Helvetica", 8)
        c.setFillColor(text_color)
        footer_text = f"Generated by SkillWise | Page {page_num} | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        c.drawCentredString(width / 2, bottom_margin + 0.1 * inch, footer_text)
        
        # Footer decorative line
        c.setStrokeColor(accent_color)
        c.setLineWidth(1)
        c.line(left_margin, bottom_margin + 0.3 * inch, width - right_margin, bottom_margin + 0.3 * inch)

    def draw_section_header(text, y_pos, is_phase=False):
        # Draw section header with enhanced styling
        if is_phase:
            c.setFont("Helvetica-Bold", 20)
            c.setFillColor(phase_color)
            line_spacing = 24
        else:
            c.setFont("Helvetica-Bold", 16)
            c.setFillColor(primary_color)
            line_spacing = 20
        
        # Draw decorative line before header
        c.setStrokeColor(accent_color)
        c.setLineWidth(1)
        c.line(left_margin, y_pos + 0.2 * inch, width - right_margin, y_pos + 0.2 * inch)
        
        # Draw header text
        y_pos = wrap_text(
            c, text, left_margin, y_pos, content_width,
            "Helvetica-Bold", 20 if is_phase else 16, line_spacing
        )
        
        # Draw decorative line after header
        c.setStrokeColor(accent_color)
        c.setLineWidth(1)
        c.line(left_margin, y_pos - 0.1 * inch, width - right_margin, y_pos - 0.1 * inch)
        
        return y_pos - 0.2 * inch

    # Initialize variables
    y_position = height - top_margin
    page_num = 1

    # Draw first page header
    draw_header()
    y_position -= 0.5 * inch

    # Enhanced title section
    title_text = "Your Personalized Learning Roadmap"
    if job_fit_analysis: # Check if it's a job-specific roadmap
        title_text = "Focused Learning Roadmap (Based on Job Description)"

    c.setFont("Helvetica-Bold", 28)
    c.setFillColor(primary_color)
    y_position = wrap_text(
        c, title_text, left_margin, y_position,
        content_width, "Helvetica-Bold", 28, line_spacing=32
    )
    y_position -= 0.3 * inch

    # Generation date with enhanced styling
    c.setFont("Helvetica", 12)
    c.setFillColor(text_color)
    y_position = wrap_text(
        c, f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} for role: {effective_role}",
        left_margin, y_position, content_width, "Helvetica", 12, line_spacing=16
    )
    y_position -= 0.4 * inch

    # Add Job Fit Analysis if available
    if job_fit_analysis:
        if y_position < bottom_margin + 3 * inch:
            draw_footer(page_num)
            c.showPage()
            page_num += 1
            draw_header()
            y_position = height - top_margin - 0.5 * inch

        y_position = draw_section_header("Job Fit Analysis", y_position, is_phase=False)
        y_position -= 0.1 * inch
        analysis_text = clean_text(job_fit_analysis)
        c.setFont("Helvetica", 10)
        c.setFillColor(text_color)
        y_position = wrap_text(c, analysis_text, left_margin + 0.2*inch, y_position, content_width - 0.2*inch, "Helvetica", 10, line_spacing=12)
        y_position -= 0.3 * inch

    # Add Smart AI Gap Analysis if available
    if smart_gap_analysis and not job_fit_analysis:
        if y_position < bottom_margin + 3 * inch:
            draw_footer(page_num)
            c.showPage()
            page_num += 1
            draw_header()
            y_position = height - top_margin - 0.5 * inch

        y_position = draw_section_header("Smart AI Gap Analysis", y_position, is_phase=False)
        y_position -= 0.1 * inch
        analysis_text = clean_text(smart_gap_analysis)
        c.setFont("Helvetica", 10)
        c.setFillColor(text_color)
        y_position = wrap_text(c, analysis_text, left_margin + 0.2*inch, y_position, content_width - 0.2*inch, "Helvetica", 10, line_spacing=12)
        y_position -= 0.3 * inch

    # Process roadmap content with enhanced styling
    lines = roadmap.splitlines()
    current_phase = None
    bullet_indent = left_margin + 0.3 * inch

    for line in lines:
        line = clean_text(line.strip())
        if not line:
            continue

        if y_position < bottom_margin + 1.5 * inch:
            draw_footer(page_num)
            c.showPage()
            page_num += 1
            draw_header()
            y_position = height - top_margin - 0.5 * inch

        if line.startswith("##"):
            text = line[2:].strip()
            y_position = draw_section_header(text, y_position, is_phase=True)
            current_phase = text

        elif line.startswith("**") and line.endswith("**"):
            text = line[2:-2].strip()
            if y_position < bottom_margin + 2 * inch:
                draw_footer(page_num)
                c.showPage()
                page_num += 1
                draw_header()
                y_position = height - top_margin - 0.5 * inch

            y_position = draw_section_header(text, y_position, is_phase=False)

        elif line.startswith("-"):
            text = line[1:].strip()
            
            if ":" in text:
                title, description = text.split(":", 1)
                title = title.strip()
                description = description.strip()
                
                c.setFont("Helvetica-Bold", 12)
                c.setFillColor(primary_color)
                y_position = wrap_text(
                    c, f"• {title}:", bullet_indent, y_position, 
                    content_width - 0.3 * inch, "Helvetica-Bold", 12, line_spacing=16
                )
                
                c.setFont("Helvetica", 11)
                c.setFillColor(text_color)
                y_position = wrap_text(
                    c, f"  {description}", bullet_indent + 0.2 * inch, y_position, 
                    content_width - 0.5 * inch, "Helvetica", 11, line_spacing=14
                )
            else:
                c.setFont("Helvetica", 12)
                c.setFillColor(text_color)
                y_position = wrap_text(
                    c, f"• {text}", bullet_indent, y_position, 
                    content_width - 0.3 * inch, "Helvetica", 12, line_spacing=16
                )

        elif line.startswith("  •"):
            text = line[3:].strip()
            
            if ":" in text:
                title, description = text.split(":", 1)
                title = title.strip()
                description = description.strip()
                
                c.setFont("Helvetica-Bold", 11)
                c.setFillColor(accent_color)
                y_position = wrap_text(
                    c, f"  ◦ {title}:", bullet_indent + 0.2 * inch, y_position, 
                    content_width - 0.5 * inch, "Helvetica-Bold", 11, line_spacing=14
                )
                
                c.setFont("Helvetica", 10)
                c.setFillColor(text_color)
                y_position = wrap_text(
                    c, f"    {description}", bullet_indent + 0.4 * inch, y_position, 
                    content_width - 0.7 * inch, "Helvetica", 10, line_spacing=12
                )
            else:
                c.setFont("Helvetica", 11)
                c.setFillColor(text_color)
                y_position = wrap_text(
                    c, f"  ◦ {text}", bullet_indent + 0.2 * inch, y_position, 
                    content_width - 0.5 * inch, "Helvetica", 11, line_spacing=14
                )

    draw_footer(page_num)
    c.save()
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
